-- Add columns to event_attendees to track "going home" status
ALTER TABLE public.event_attendees 
ADD COLUMN IF NOT EXISTS going_home_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS destination_name TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS destination_lat DOUBLE PRECISION DEFAULT NULL,
ADD COLUMN IF NOT EXISTS destination_lng DOUBLE PRECISION DEFAULT NULL,
ADD COLUMN IF NOT EXISTS arrived_home BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;